[package]
name = "ssh-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
async-trait = "0.1.83"
clap = {version="4.5.20", features=["derive"]}
env_logger = "0.11.5"
log = "0.4.22"
regex = "1.11.0"
russh = "0.45.0"
tokio = {version="1.40.0", features=["io-std"]}
